repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/psf/black
    rev: 21.11b0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
