name: chiron
channels:
  - defaults
  - conda-forge
dependencies:
  - black-jupyter
  - boto3
  - isort
  - kaggle
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - pre-commit
  - pylama
  - pylint
  - python=3.8
  - pyyaml
  - scikit-learn
  - tensorflow-gpu
  - tensorflow-estimator=2.5.0
  - tensorflow-hub=0.12.0
  - pip:
      - commitizen
variables:
  KAGGLE_USERNAME: mattmolinare
  KAGGLE_KEY: f597cadbd1e2c019a0ce73a49cbbad63
