name: chiron
channels:
  - defaults
  - conda-forge
dependencies:
  - black-jupyter
  - isort
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - pre-commit
  - pylama
  - pylint
  - python
  - pyyaml
  - scikit-learn
  - tensorflow-gpu
  - tensorflow-estimator=2.5.0
  - tensorflow-hub=0.12.0
  - pip:
      - commitizen
