name: chiron
channels:
  - conda-forge
  - defaults
dependencies:
  - black-jupyter
  - isort
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - pre-commit
  - pylama
  - pylint
  - pyyaml
  - tensorflow-gpu
  - tensorflow-hub
  - pip:
      - commitizen
