image_size: [224, 224]
num_epochs: 100
batch_size_per_device: 32
shuffle_buffer_size: 1024
lr: 0.00003
reduce_lr_patience: 4
early_stopping_patience: 16
reg_scale: null
save_period: 5
classes:
  - label: meningioma
    orig_labels:
      - meningioma
  - label: glioma
    orig_labels:
      - glioma
  - label: pituitary
    orig_labels:
      - pituitary
  - label: notumor
    orig_labels:
      - notumor
