image_size: [224, 224]
num_epochs: 40
batch_size_per_device: 32
shuffle_buffer_size: null
base_lr: 1.0e-6
max_lr: 1.0e-4
clr_step_size: 2500
grad_clip: 1.0
early_stopping_patience: 16
dropout_rate: 0.2
reg_scale: 0.01
run_eagerly: False
save_interval: 5
classes:
  - label: meningioma
    orig_labels:
      - meningioma
  - label: glioma
    orig_labels:
      - glioma
  - label: pituitary
    orig_labels:
      - pituitary
